#!/usr/bin/env bash
git pull \
  && make clean distclean \
  && make breach \
  ;  \
  git add -A \
  && git commit -v -m"breach (armhf)" \
  && sudo dpkg -i urbit_0.2*.deb \
  && git push \
  && \
  git reset --hard
